### ISSUE TITLE
openbl memory and flash usage

### ISSUE THREAD

**Issue by arilink** [STMicroelectronics/stm32-mw-openbl#1]
I learned that OPenbootloader has been updated and has reached the 6th version. When I opened STM32CubeU5, I found that OPENBL_RAM_SIZE is 90kBytes. Is there any detailed document to explain how to cut this BootLoader, because chips with small resources cannot use this bootloader at all

**Comment by ALAASTM** [comment]
Hi @arilink-tech

The Open Bootloader RAM size depends on the number on supported protocols (USART, SPI…), memories (FLASH, SRAM…) and amount of code used.

In case of U5, the provided application supports 5 protocols, 6 memories and besides that it is based on Threadx to be able to support USBx, this is why it needs 90K.

In a product with small RAM, the user can easily adapt the application and remove protocols or memories that he don’t need and save RAM.

For example, you can check the Open Bootloader application of WL in [WL Open Bootloader GitHub Page](https://github.com/STMicroelectronics/stm32wl-openbl-apps), this application only supports USART and SP1 and `only needs 6k` of RAM.

You can check the `app_openbootloader.c` file under `…\Applications\OpenBootloader\OpenBootloader\App\` for more details about how to add or remove protocols or memories.

Hope this helps.
