### ISSUE TITLE
Why is the compatibility of openbl so poor?

### ISSUE THREAD

**Issue by arilink** [STMicroelectronics/stm32-mw-openbl#2]
According to the content described in the readme, openbl should be a bootloader compatible with all stm32 chips. However, when I transplanted openbl to stm32f1 following the program of stm32u5, there were a lot of errors. The flash_interface should be a file compatible with all devices. , but now there are so many errors I don't know how to fix it

**Comment by ALAASTM** [comment]
Hi @arilink-tech

The Open Bootloader MW part is HW independent and will not need porting from one device to another as its code doesn’t access directly to HW resources.

However, from one product to another we need to update the application code that provides to MW code the access to HW resources.

So, interfaces files like `flash_interface.c`, `usart_interface.c`, `ram_interface.c`… contain code that has access to HW this is why it must be ported from one device to another.
In general, the code that is under `…\Applications\OpenBootloader\OpenBootloader\Targer\` is HW dependent.

You can for example compare these two applications to understand how porting is done from one device to another:
- [WL Open Bootloader GitHub Page](https://github.com/STMicroelectronics/stm32wl-openbl-apps)
- [L5 Open Bootloader GitHub Page](https://github.com/STMicroelectronics/stm32l5-openbl-apps)

Hope this helps
