### ISSUE TITLE
Some functions are placed in the RAM

### ISSUE THREAD

**Issue by giacominconsulting** [STMicroelectronics/stm32-mw-openbl#3]
Hello,

could you please explain why in the file spi_interface.c some functions are placed in the RAM ?
For exaple:
#if defined (__ICCARM__)
__ramfunc void OPENBL_SPI_SendByte(uint8_t Byte)
#else
__attribute__((section(".ramfunc"))) void OPENBL_SPI_SendByte(uint8_t Byte)
#endif /* (__ICCARM__) */

Thank you for your help.
Regards,
Marco

**Comment by ALAASTM** [comment]
Hello @giacominconsulting,

Sorry for the very late response.

We need to place some functions in RAM to be able to call them when FLASH is being erased for example.

Some FLASH operations like page erase, mass erase… stop the FLASH from responding until the operation is done.
For example, mass erase operation, and depending on the product, may take several seconds to finish.

The delivered application is compiled in FLASH, so, for example, during a mass erase operation the CPU will not be able to fetch instructions rom FLASH as it is being erased.
To be able to respond to the SPI host, we place some functions in RAM, so they continue to work even if the FLASF is being erased.

Hope this clarify the use of RAM functions.

Best regards.
