### ISSUE TITLE
Support of High Speed USB 

### ISSUE THREAD

**Issue by jeff-jldtech** [STMicroelectronics/stm32-mw-openbl#4]
Support for the High Speed USB interface?

Currently using the STM32H743I-EVAL2 board and would like to use the openbl on the high speed usb interface instead of the full speed usb port.

Developing in the STM32CUBE IDE.

**Comment by ALAASTM** [comment]
Hi @jeff-jldtech,

The MW component is independent from HW. So, in the implementation there is nothing that need to be changed to support USB full speed.

The changes must be done in application side and for that you can easily take any USB application from STM32H743I-EVAL2 and use its configuration to configure the USB.

Note that we are working to deliver an Open Bootloader application for H7 in incoming weeks.

Best regards.
