### ISSUE TITLE
Where is Get Memory Checksum command (i2c interface)

### ISSUE THREAD

**Issue by kjsdf7wr3** [STMicroelectronics/stm32-mw-openbl#5]
According to AN4221, the i2c bootloaders starting from version 1.2 support "No-Stretch Get Memory Checksum" command. However, I simply cannot find that command implementation or handling in the files ```modules/i2c/openbl_i2c.cmd.h``` or ```modules/i2c/openbl_i2c.cmd.h```

**Comment by kjsdf7wr3** [comment]
It appears that ST does not react to issues here, so I made a similar post in the forums: https://community.st.com/s/question/0D53W00001jlKwXSAU/stm32mwopenbl-missing-functionality-getchecksum-maybe-more

**Comment by ALAASTM** [comment]
Hello @kjsdf7wr3,

Sorry for the very late response.

This command is not yet implemented in Open Bootloader MW and its implementation is planned for upcoming releases.

This command is not widely used and not implemented in all products, so its implementation was not a priority.

Best regards.
